version: 1
updated_at: "2026-07-28"
aliases:
  "Bilibili": "Bilibili Gaming"
  "Invictus": "Invictus Gaming"
  "Weibo": "Weibo Gaming"
  "ThunderTalk": "ThunderTalk Gaming"
  "LGD": "LGD Gaming"
  "LNG": "LNG Esports"
  "Hanwha Life": "Hanwha Life Esports"
  "DRX": "Kiwoom DRX"
  "DN Freecs": "DN SOOPers"
  "OKSavingsBank BRION": "HANJIN BRION"
  "Liquid": "Team Liquid"
  "G2": "G2 Esports"
  "Heretics": "Team Heretics"
  "Vitality": "Team Vitality"
  "BDS": "Team BDS"
  "Heretics Academy": "Team Heretics Academy"
  "Los Heretics": "Team Heretics Academy"
  "Ici Japon Corp": "Ici Japon Corp. Esport"
  "Lausanne-Sport": "Lausanne-Sport Esports"
  "BK ROG": "BK ROG Esports"
  "Zephyr": "Zephyr Esport"
  "Caldya": "Caldya Esport"
  "Lille": "Lille Esport"
  "Barca": "Barça eSports"
  "Barça": "Barça eSports"
  "Falke": "Falke Esports"
  "UCAM": "UCAM Esports"
  "LUA": "LUA Gaming"
  "ZYB": "ZYB Esport"
  "Ramboot": "Ramboot Club"
  "paiN": "paiN Gaming"
