version: 1

target_leagues:
  - LCK
  - LPL
  - LEC
  - CBLOL
  - LCS
  - LFL
  - LES
  - TCL
  - PRM

canonical_mapping:
  LCK: LCK
  LPL: LPL
  LEC: LEC
  CBLOL: CBLOL
  LCS: LCS
  LFL: LFL
  LVP SL: LES
  LES: LES
  TCL: TCL
  PRM: PRM
  LTA N: LCS
  LTA S: CBLOL

auxiliary_competitions:
  - LTA
  - MSI
  - WLDs
  - FST
  - EWC
  - IC
  - DCup
  - KeSPA
  - KeSPA Cup
